---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: "((readonly_private_ecr_repo_url))"
    tag: concourse-builder-latest

# https://github.com/concourse/builder-task#params
params:
  # docker-compose, "<directory name>_<service name>"
  REPOSITORY: 'src_app'
  CONTEXT: 'src'
  BUILD_ARG_BUNDLE_INSTALL_CMD: 'bundle install --jobs 20 --retry 5'
  TAG: latest

inputs:
  - name: src

outputs:
  - name: docker-cache/app-prebuilt

caches:
  - path: cache

run:
  path: bash
  args:
    - '-exvc'
    - |
      mkdir -p image
      build
      mv image/image.tar docker-cache/app-prebuilt/image.tar
